# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2060f25e42ec492f8b2dff2de24bc973f5e9984c33b6c73b2911ddad700a4f3844e72b98afd7590bf35175e9dee9a4ef5c80aba8237d2f69802820f621ea5ede

test:
  secret_key_base: 5a59bf3e45d7825b896103c4964f78533e7358e72aa89030fcdc2601f89e85ae45997b567c155e44105348a28fff2b2e8de0220d92ba733d7b05d4fdc4d10b5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
