# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1418fd7a37de015d9930e5f700d22997a32e3bd9810926bca6b089000464edd99003fde1154e63a725188f20e3415d7ddfe339be67f9407f400c15ca7c2e6c62

test:
  secret_key_base: fa6d3c825353f0209b7b02eaeaf253e39a06ea8dbd79e898f0f1f4900f693ba71b654046f29a798da61ec9d92a4194c44ae119dc800e71e27728bfa50e942197

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
