# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da7aee63cbd8f80c1d021bff7021a3497217b2d0695c229fbc33c86f4f0ec45671af914f8e47dc6046a6087a3d15faaeed369314cd087a89c1066663d7da2a9f

test:
  secret_key_base: acf524d0f1609c297098627d6a8fe862d541d32c75c096c3104ed967672337f802d1b9fd01f6d933cb797ae7f02f8c21a653040311785afabd7dc608d2ef26b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
